### ISSUE TITLE
updating package.json and READE.md for aurelia-vi-grid verson 0.2.6

### ISSUE THREAD

**Issue by mingqin1** [aurelia-ui-toolkits/demo-v-grid#1]
The original pacakge.json has this line "aurelia-v-grid": "github:aurelia-ui-toolkits/aurelia-v-grid@master" to import aurelia-v-grid library based on master branch,   the project failed to start up.

Once replacing with "aurelia-v-grid": "github:aurelia-ui-toolkits/aurelia-v-grid@^0.2.6", the project starts up .

READE.md will be better to have detail instructions of installing needed libraries , such as
1. at root directory, run  "npm install"
2. at root directory, run "jspm install"
3. at root directory, run "gulp watch"

**Comment by vegarringdal** [comment]
thanks, but..
This is just for the gh-pages  for demo link on https://github.com/aurelia-ui-toolkits/aurelia-v-grid/
Not to be used downloaded and used. Its the same demo thats included in the sample folder in main repo.
Since I havent changed the demo, how it works this repo have not been updated, been trying to stick to gist more since its easier for people to use and do changes.
https://aurelia-ui-toolkits.gitbooks.io/aurelia-v-grid-docs/content/chap02/live_demo_and_gistrun.html

**Comment by mingqin1** [comment]
The aurelia-v-grid doc mentioned how to install aureli-v-grid to JSPM and Webpack projects with examples of      skeleton-esnext-webpack and     skeleton-esnext.   I tried on both skeleton-\* projects with migrating aurelia-v-grid sample codes into them.  Those converting efforts failed on recognizing prism library when shared/au-code.js references prism library though I modified package.json to add extra libraries being needed for sample codes.
  The demo-v-grid as JSPM-based project gave a right configuration on package.json or other configurations which served as  a reference for other JSPM projects to have configuration on package.json  and other configurations when installing aurelia-v-grid into users' own projects occurs. thanks

**Comment by vegarringdal** [comment]
Hi

But unsure where this is going.
But for sample code you could copy into own project it would be simple just to copy code from one of the gist samples , like this one if you need to generate dummy data etc:

https://gist.run/?id=fbd4e9f36d5eacd120dfac8184601f8d

Feel free to ask me more on gitter channel if you have more questions.
